REPO_ID = "EleutherAI/pile-standard-pythia-preshuffled"

CONTEXT_LENGTH = 1024

NUM_GPUS = 8

BATCH_SIZE = 32
GRAD_ACCUM_STEPS = 8 // NUM_GPUS
EFFECTIVE_BATCH_SIZE = 256
assert EFFECTIVE_BATCH_SIZE == BATCH_SIZE * GRAD_ACCUM_STEPS * NUM_GPUS
