REPO_ID = "EleutherAI/pile-standard-pythia-preshuffled"

CONTEXT_LENGTH = 1024

BATCH_SIZE = 16
GRAD_ACCUM_STEPS = 16
EFFECTIVE_BATCH_SIZE = 256
assert EFFECTIVE_BATCH_SIZE == BATCH_SIZE * GRAD_ACCUM_STEPS

DEEPSPEED_GRAD_ACCUM_STEPS = 8